"""
Symbol and Dependency Analyzer for extracting symbols and mapping dependencies.
"""

from __future__ import annotations

import ast
import json
import re
import toml
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Set, Optional, Any, Tuple
from collections import defaultdict


@dataclass
class Symbol:
    """Represents a symbol (function, class, variable) in the codebase."""
    name: str
    symbol_type: str  # 'function', 'class', 'variable', 'import', etc.
    file_path: Path
    line_number: int
    column: int = 0
    end_line_number: Optional[int] = None
    end_column: int = 0
    scope: str = ""  # e.g., "module", "class.MyClass", "function.my_func"
    is_definition: bool = True
    is_exported: bool = False
    is_imported: bool = False
    aliases: List[str] = field(default_factory=list)
    # For imports/exports
    imported_from: Optional[Path] = None
    imported_name: Optional[str] = None
    exported_as: Optional[str] = None


@dataclass
class DependencyEdge:
    """Represents a dependency relationship between files."""
    source_file: Path
    target_file: Path
    dependency_type: str  # 'import', 'require', 'include', etc.
    symbol_name: Optional[str] = None
    line_number: int = 0
    # For configuration-based dependencies
    dependency_spec: Optional[str] = None  # e.g., "lodash^4.17.21"
    is_resolved: bool = True
    weight: float = 1.0  # Strength of dependency (for weighting)


@dataclass
class SpecialFileClassification:
    """Classification of a file as special type."""
    file_path: Path
    is_generated: bool = False
    is_large: bool = False
    is_binary: bool = False
    size_lines: int = 0
    size_bytes: int = 0
    confidence: float = 0.0  # Confidence in classification (0.0-1.0)
    reasons: List[str] = field(default_factory=list)


class SymbolDependencyAnalyzer:
    """
    Analyzes symbols and dependencies in the codebase.

    Provides:
    - Symbol extraction using AST parsing (with regex fallback)
    - Import/export/require statement analysis
    - Configuration-driven dependency extraction
    - Basic call graph construction
    - Special file type detection and classification
    """

    def __init__(self, workspace):
        """
        Initialize the symbol and dependency analyzer.

        Args:
            workspace: The workspace instance to operate within
        """
        self.workspace = workspace
        self._symbol_cache: Dict[Path, List[Symbol]] = {}
        self._dependency_cache: Dict[Path, List[DependencyEdge]] = {}
        self._special_file_cache: Dict[Path, SpecialFileClassification] = {}

        # Language-specific patterns for import/export statements
        self.import_patterns = {
            'python': [
                r'^\s*import\s+([a-zA-Z_][a-zA-Z0-9_]*(?:\s*,\s*[a-zA-Z_][a-zA-Z0-9_]*)*)',
                r'^\s*from\s+([a-zA-Z_.][a-zA-Z0-9_.]*)\s+import\s+(.+)',
            ],
            'javascript': [
                r'^\s*import\s+.*?\s+from\s+[\'"]([^\'"]+)[\'"]',
                r'^\s*import\s+[\'"]([^\'"]+)[\'"]',
                r'^\s*require\s*\(\s*[\'"]([^\'"]+)[\'"]\s*\)',
            ],
            'typescript': [
                r'^\s*import\s+.*?\s+from\s+[\'"]([^\'"]+)[\'"]',
                r'^\s*import\s+[\'"]([^\'"]+)[\'"]',
                r'^\s*require\s*\(\s*[\'"]([^\'"]+)[\'"]\s*\)',
                r'^\s*export\s+.*?\s+from\s+[\'"]([^\'"]+)[\'"]',
            ],
            'java': [
                r'^\s*import\s+([a-zA-Z_][a-zA-Z0-9_.]*(?:\s*\*\s*)?);',
            ],
            'go': [
                r'^\s*import\s+(?:\s*[\'"]([^\'"]+)[\'"]\s*|\s*\([^)]*\))',
            ],
            'ruby': [
                r'^\s*require\s*[\'"]([^\'"]+)[\'"]',
                r'^\s*require_relative\s*[\'"]([^\'"]+)[\'"]',
            ],
            'php': [
                r'^\s*require(?:_once)?\s*[\'"]([^\'"]+)[\'"]',
                r'^\s*include(?:_once)?\s*[\'"]([^\'"]+)[\'"]',
            ],
        }

        # Configuration file parsers
        self.config_parsers = {
            'package.json': self._parse_package_json,
            'Cargo.toml': self._parse_cargo_toml,
            'pom.xml': self._parse_pom_xml,  # Simplified
            'requirements.txt': self._parse_requirements_txt,
            'setup.py': self._parse_setup_py,  # Simplified
            'poetry.lock': self._parse_poetry_lock,  # Simplified
        }

        # Special file detection patterns
        self.generated_file_headers = [
            r'# Generated by',
            r'// Generated by',
            r'/\* Generated by',
            r'# DO NOT EDIT',
            r'// DO NOT EDIT',
            r'/\* DO NOT EDIT',
            r'# AUTOGENERATED',
            r'// AUTOGENERATED',
            r'/\* AUTOGENERATED',
        ]

        self.generated_dirs = {
            'gen', 'generated', 'built', 'build', 'dist', 'output',
            'target', 'bin', 'obj', 'out'
        }

        self.generated_patterns = [
            r'\.generated\.',
            r'\.pb\.(go|py|java)',
            r'\.pb\.go$',
            r'\.pb\.py$',
            r'\.pb\.java$',
            r'\.min\.(js|css)$',
            r'\.bundle\.(js|css)$',
        ]

    def analyze_file_symbols(self, file_path: Path) -> List[Symbol]:
        """
        Extract symbols from a file using AST parsing or regex fallback.

        Args:
            file_path: Path to the file to analyze

        Returns:
            List of Symbol objects found in the file
        """
        # Check cache first
        if file_path in self._symbol_cache:
            return self._symbol_cache[file_path]

        symbols = []

        # Ensure file is within workspace
        if not self._is_within_workspace(file_path):
            return symbols

        # Try to get file content
        try:
            content = file_path.read_text(encoding='utf-8', errors='ignore')
        except (OSError, IOError, UnicodeDecodeError):
            return symbols

        # Determine file type
        file_type = self._get_file_type(file_path)

        # Try AST parsing first for supported languages
        if file_type in ['python']:
            try:
                symbols.extend(self._extract_symbols_python_ast(file_path, content))
            except SyntaxError:
                # Fall back to regex if AST parsing fails
                symbols.extend(self._extract_symbols_regex(file_path, content, file_type))
        else:
            # Use regex fallback for other languages
            symbols.extend(self._extract_symbols_regex(file_path, content, file_type))

        # Extract import/export dependencies
        symbols.extend(self._extract_import_export_symbols(file_path, content, file_type))

        # Cache and return
        self._symbol_cache[file_path] = symbols
        return symbols

    def analyze_file_dependencies(self, file_path: Path) -> List[DependencyEdge]:
        """
        Analyze dependencies for a file.

        Args:
            file_path: Path to the file to analyze

        Returns:
            List of DependencyEdge objects representing dependencies
        """
        # Check cache first
        if file_path in self._dependency_cache:
            return self._dependency_cache[file_path]

        dependencies = []

        # Ensure file is within workspace
        if not self._is_within_workspace(file_path):
            return dependencies

        # Try to get file content
        try:
            content = file_path.read_text(encoding='utf-8', errors='ignore')
        except (OSError, IOError, UnicodeDecodeError):
            return dependencies

        # Determine file type
        file_type = self._get_file_type(file_path)

        # Extract import/export dependencies
        dependencies.extend(self._extract_import_export_dependencies(file_path, content, file_type))

        # Check if this is a configuration file and extract dependencies from it
        if file_path.name in self.config_parsers:
            dependencies.extend(self._extract_config_dependencies(file_path))

        # Cache and return
        self._dependency_cache[file_path] = dependencies
        return dependencies

    def classify_special_file(self, file_path: Path) -> SpecialFileClassification:
        """
        Classify a file as special type (generated, large, binary, etc.).

        Args:
            file_path: Path to the file to classify

        Returns:
            SpecialFileClassification object
        """
        # Check cache first
        if file_path in self._special_file_cache:
            return self._special_file_cache[file_path]

        # Initialize classification
        classification = SpecialFileClassification(file_path=file_path)

        # Ensure file is within workspace
        if not self._is_within_workspace(file_path):
            return classification

        try:
            # Get file stats
            stat = file_path.stat()
            classification.size_bytes = stat.st_size

            # Try to get line count for text files
            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    classification.size_lines = sum(1 for _ in f)
            except (OSError, IOError):
                # If we can't read as text, estimate or leave as 0
                classification.size_lines = 0

            # Check for binary file
            classification.is_binary = self._is_binary_file(file_path)

            # Check for large file
            classification.is_large = self._is_large_file(file_path, classification.size_lines, classification.size_bytes)

            # Check for generated file
            gen_result = self._is_generated_file(file_path)
            classification.is_generated = gen_result['is_generated']
            classification.confidence = gen_result['confidence']
            classification.reasons = gen_result['reasons']

        except (OSError, IOError):
            # If we can't stat the file, return default classification
            pass

        # Cache and return
        self._special_file_cache[file_path] = classification
        return classification

    def build_dependency_graph(self, file_paths: List[Path]) -> Dict[Path, List[DependencyEdge]]:
        """
        Build a dependency graph for the given files.

        Args:
            file_paths: List of file paths to analyze

        Returns:
            Dictionary mapping file paths to their dependencies
        """
        graph = {}

        for file_path in file_paths:
            # Ensure file is within workspace
            if self._is_within_workspace(file_path):
                dependencies = self._analyze_file_dependencies_cached(file_path)
                graph[file_path] = dependencies

        return graph

    def detect_circular_dependencies(self, file_paths: List[Path]) -> List[List[Path]]:
        """
        Detect circular dependencies in the given files.

        Args:
            file_paths: List of file paths to analyze

        Returns:
            List of circular dependency paths (each inner list is a cycle)
        """
        # Build dependency graph
        graph = self.build_dependency_graph(file_paths)

        # Convert to adjacency list for DFS
        adj_list = defaultdict(list)
        file_to_index = {file_path: i for i, file_path in enumerate(file_paths)}

        for source_file, dependencies in graph.items():
            if source_file in file_to_index:
                source_idx = file_to_index[source_file]
                for dep in dependencies:
                    if dep.target_file in file_to_index:
                        target_idx = file_to_index[dep.target_file]
                        adj_list[source_idx].append(target_idx)

        # Find cycles using DFS
        visited = [False] * len(file_paths)
        rec_stack = [False] * len(file_paths)
        cycles = []
        path = []

        def dfs(node_idx: int, path_so_far: List[int]):
            visited[node_idx] = True
            rec_stack[node_idx] = True
            path_so_far.append(node_idx)

            for neighbor_idx in adj_list[node_idx]:
                if not visited[neighbor_idx]:
                    dfs(neighbor_idx, path_so_far)
                elif rec_stack[neighbor_idx]:
                    # Found a cycle
                    cycle_start = path_so_far.index(neighbor_idx)
                    cycle_indices = path_so_far[cycle_start:]
                    cycle_files = [file_paths[i] for i in cycle_indices]
                    cycles.append(cycle_files)

            rec_stack[node_idx] = False
            path_so_far.pop()

        # Run DFS from each unvisited node
        for i in range(len(file_paths)):
            if not visited[i]:
                dfs(i, [])

        return cycles

    # Private helper methods

    def _is_within_workspace(self, file_path: Path) -> bool:
        """Check if a file path is within the workspace boundaries."""
        try:
            if isinstance(file_path, str):
                file_path = Path(file_path)
            resolved_file = file_path.resolve()
            resolved_workspace = Path(self.workspace.workspace_root).resolve()
            return resolved_workspace in resolved_file.parents or resolved_file == resolved_workspace
        except (OSError, ValueError):
            return False

    def _get_file_type(self, file_path: Path) -> str:
        """Determine the file type based on extension."""
        suffix = file_path.suffix.lower()

        # Map extensions to language types
        extension_map = {
            '.py': 'python',
            '.js': 'javascript',
            '.ts': 'typescript',
            '.jsx': 'javascript',
            '.tsx': 'typescript',
            '.rs': 'rust',
            '.java': 'java',
            '.go': 'go',
            '.rb': 'ruby',
            '.php': 'php',
            '.cs': 'csharp',
            '.cpp': 'cpp',
            '.c': 'c',
            '.h': 'c',
            '.hpp': 'cpp',
        }

        return extension_map.get(suffix, 'unknown')

    def _extract_symbols_python_ast(self, file_path: Path, content: str) -> List[Symbol]:
        """Extract symbols from Python file using AST."""
        symbols = []

        try:
            tree = ast.parse(content)
        except SyntaxError:
            return symbols

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                symbols.append(Symbol(
                    name=node.name,
                    symbol_type='function',
                    file_path=file_path,
                    line_number=node.lineno,
                    column=node.col_offset,
                    end_line_number=getattr(node, 'end_lineno', node.lineno),
                    end_column=getattr(node, 'end_col_offset', node.col_offset + len(node.name)),
                    scope='module',
                    is_definition=True
                ))

                # Extract arguments as variables
                for arg in node.args.args:
                    symbols.append(Symbol(
                        name=arg.arg,
                        symbol_type='variable',
                        file_path=file_path,
                        line_number=node.lineno + 1,  # Approximate
                        scope=f'function.{node.name}',
                        is_definition=True
                    ))

            elif isinstance(node, ast.AsyncFunctionDef):
                symbols.append(Symbol(
                    name=node.name,
                    symbol_type='function',
                    file_path=file_path,
                    line_number=node.lineno,
                    column=node.col_offset,
                    end_line_number=getattr(node, 'end_lineno', node.lineno),
                    end_column=getattr(node, 'end_col_offset', node.col_offset + len(node.name)),
                    scope='module',
                    is_definition=True
                ))

            elif isinstance(node, ast.ClassDef):
                symbols.append(Symbol(
                    name=node.name,
                    symbol_type='class',
                    file_path=file_path,
                    line_number=node.lineno,
                    column=node.col_offset,
                    end_line_number=getattr(node, 'end_lineno', node.lineno),
                    end_column=getattr(node, 'end_col_offset', node.col_offset + len(node.name)),
                    scope='module',
                    is_definition=True
                ))

            elif isinstance(node, ast.Assign):
                # Extract variable assignments
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        symbols.append(Symbol(
                            name=target.id,
                            symbol_type='variable',
                            file_path=file_path,
                            line_number=node.lineno,
                            column=getattr(target, 'col_offset', 0),
                            scope='module',
                            is_definition=True
                        ))
                    elif isinstance(target, ast.Attribute):
                        # Skip attribute assignments for simplicity
                        pass

            elif isinstance(node, ast.Import):
                for alias in node.names:
                    symbols.append(Symbol(
                        name=alias.name,
                        symbol_type='import',
                        file_path=file_path,
                        line_number=node.lineno,
                        column=node.col_offset,
                        scope='module',
                        is_definition=False,
                        is_imported=True,
                        imported_name=alias.asname or alias.name
                    ))

            elif isinstance(node, ast.ImportFrom):
                module_name = node.module or ''
                for alias in node.names:
                    symbols.append(Symbol(
                        name=alias.name,
                        symbol_type='import_from',
                        file_path=file_path,
                        line_number=node.lineno,
                        column=node.col_offset,
                        scope='module',
                        is_definition=False,
                        is_imported=True,
                        imported_name=alias.asname or alias.name,
                        imported_from=self._resolve_import_path(file_path, module_name) if module_name else None
                    ))

        return symbols

    def _extract_symbols_regex(self, file_path: Path, content: str, file_type: str) -> List[Symbol]:
        """Extract symbols using regex patterns as fallback."""
        symbols = []
        lines = content.splitlines()

        # Language-specific patterns for function/class detection
        patterns = {
            'python': [
                (r'^\s*def\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*async\s+def\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*class\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*[:\(]', 'class'),
            ],
            'javascript': [
                (r'^\s*function\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*const\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(?:async\s+)?\s*\(', 'function'),
                (r'^\s*let\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(?:async\s+)?\s*\(', 'function'),
                (r'^\s*var\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(?:async\s+)?\s*\(', 'function'),
                (r'^\s*class\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'class'),
            ],
            'typescript': [
                (r'^\s*function\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*const\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(?:async\s+)?\s*\(', 'function'),
                (r'^\s*let\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(?:async\s+)?\s*\(', 'function'),
                (r'^\s*var\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(?:async\s+)?\s*\(', 'function'),
                (r'^\s*class\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'class'),
                (r'^\s*interface\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'interface'),
                (r'^\s*type\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=', 'type_alias'),
            ],
            'java': [
                (r'^\s*(?:public\s+|private\s+|protected\s+)?\s*(?:static\s+)?\s*\w+\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*(?:public\s+|private\s+|protected\s+)?\s*class\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'class'),
                (r'^\s*(?:public\s+|private\s+|protected\s+)?\s*interface\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'interface'),
            ],
            'go': [
                (r'^\s*func\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*type\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*struct\s*{', 'struct'),
                (r'^\s*type\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*interface\s*{', 'interface'),
            ],
            'rust': [
                (r'^\s*fn\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*struct\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*{', 'struct'),
                (r'^\s*enum\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*{', 'enum'),
                (r'^\s*struct\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*;', 'struct'),
                (r'^\s*enum\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*;', 'enum'),
                (r'^\s*type\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=', 'type_alias'),
            ],
            'cpp': [
                (r'^\s*(?:virtual\s+)?\s*\w+\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*class\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'class'),
                (r'^\s*struct\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*{', 'struct'),
            ],
            'c': [
                (r'^\s*\w+\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*struct\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*{', 'struct'),
                (r'^\s*enum\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*{', 'enum'),
            ],
            'ruby': [
                (r'^\s*def\s+([a-zA-Z_][a-zA-Z0-9_]*)', 'function'),
                (r'^\s*class\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'class'),
                (r'^\s*module\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'module'),
            ],
            'php': [
                (r'^\s*function\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', 'function'),
                (r'^\s*class\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'class'),
                (r'^\s*interface\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*', 'interface'),
            ],
        }

        file_patterns = patterns.get(file_type, [])

        for line_num, line in enumerate(lines, 1):
            for pattern, symbol_type in file_patterns:
                match = re.search(pattern, line)
                if match:
                    name = match.group(1)
                    symbols.append(Symbol(
                        name=name,
                        symbol_type=symbol_type,
                        file_path=file_path,
                        line_number=line_num,
                        column=match.start(),
                        scope='module',
                        is_definition=True
                    ))
                    break  # Only match one pattern per line to avoid duplicates

        return symbols

    def _extract_import_export_symbols(self, file_path: Path, content: str, file_type: str) -> List[Symbol]:
        """Extract import/export symbols from file content."""
        symbols = []
        lines = content.splitlines()

        patterns = self.import_patterns.get(file_type, [])

        for line_num, line in enumerate(lines, 1):
            for pattern in patterns:
                matches = re.finditer(pattern, line)
                for match in matches:
                    # Handle different pattern structures
                    if file_type == 'python':
                        if line.strip().startswith('from'):
                            # from module import name
                            module_part = match.group(1)
                            if module_part:
                                # For relative imports, we need to resolve the full module spec
                                if module_part.startswith("."):
                                    # Relative import: resolve module_part + "." + first_item (without aliases)
                                    first_item = match.group(2).split(",")[0].strip() if match.group(2) else ""
                                    base_item = first_item.split(" as ")[0].strip()  # Get actual module name, not alias
                                    full_module_spec = module_part + base_item
                                    target_file = self._resolve_import_path(file_path, full_module_spec)
                                else:
                                    # Absolute import: resolve just the module_part (existing behavior)
                                    target_file = self._resolve_import_path(file_path, module_part)
                                if target_file:
                                    # Extract first imported item for symbol name
                                        first_item = match.group(2).split(",")[0].strip() if match.group(2) else ""
                                        # Handle "import as" case - take the actual alias if present, otherwise the module name
                                        if " as " in first_item:
                                            symbol_name = first_item.split(" as ")[1].strip()  # Get alias
                                        else:
                                            symbol_name = first_item.split()[0].strip() if first_item else ""  # Get module name
                                        dependencies.append(DependencyEdge(
                                            source_file=file_path,
                                            target_file=target_file,
                                            dependency_type='import_from',
                                            symbol_name=symbol_name,
                                            line_number=line_num,
                                            weight=0.8
                                        ))
                        else:
                            # import module
                            imported_names = match.group(1).split(',')
                            for name in imported_names:
                                name = name.strip()
                                if name:
                                    symbols.append(Symbol(
                                        name=name,
                                        symbol_type='import',
                                        file_path=file_path,
                                        line_number=line_num,
                                        column=match.start(),
                                        scope='module',
                                        is_definition=False,
                                        is_imported=True,
                                        imported_name=name
                                    ))
                    else:
                        # For other languages, capture the imported module/path
                        imported_path = match.group(1)
                        if imported_path:
                            symbols.append(Symbol(
                                name=imported_path,
                                symbol_type='import',
                                file_path=file_path,
                                line_number=line_num,
                                column=match.start(),
                                scope='module',
                                is_definition=False,
                                is_imported=True,
                                imported_name=imported_path
                            ))

        return symbols

    def _extract_import_export_dependencies(self, file_path: Path, content: str, file_type: str) -> List[DependencyEdge]:
        """Extract import/export dependencies from file content."""
        dependencies = []
        lines = content.splitlines()

        patterns = self.import_patterns.get(file_type, [])

        for line_num, line in enumerate(lines, 1):
            for pattern in patterns:
                matches = re.finditer(pattern, line)
                for match in matches:
                    # Handle different pattern structures
                    if file_type == 'python':
                        if line.strip().startswith('from'):
                            # from module import name
                            module_part = match.group(1)
                            if module_part:
                                # For relative imports, we need to resolve the full module spec
                                if module_part.startswith("."):
                                    # Relative import: resolve module_part + "." + first_item (without aliases)
                                    first_item = match.group(2).split(",")[0].strip() if match.group(2) else ""
                                    base_item = first_item.split(" as ")[0].strip()  # Get actual module name, not alias
                                    full_module_spec = module_part + base_item
                                    target_file = self._resolve_import_path(file_path, full_module_spec)
                                else:
                                    # Absolute import: resolve just the module_part (existing behavior)
                                    target_file = self._resolve_import_path(file_path, module_part)
                                if target_file:
                                    # Extract first imported item for symbol name
                                    first_item = match.group(2).split(",")[0].strip() if match.group(2) else ""
                                    # Handle "import as" case - take the actual alias if present, otherwise the module name
                                    if " as " in first_item:
                                        symbol_name = first_item.split(" as ")[1].strip()  # Get alias
                                    else:
                                        symbol_name = first_item.split()[0].strip() if first_item else ""  # Get module name
                                    dependencies.append(DependencyEdge(
                                        source_file=file_path,
                                        target_file=target_file,
                                        dependency_type='import_from',
                                        symbol_name=symbol_name,
                                        line_number=line_num,
                                        weight=0.8
                                    ))
                        else:
                            # import module
                            imported_names = match.group(1).split(',')
                            for name in imported_names:
                                name = name.strip()
                                if name:
                                    # Try to resolve the module to a file
                                    target_file = self._resolve_import_path(file_path, name)
                                    if target_file:
                                        dependencies.append(DependencyEdge(
                                            source_file=file_path,
                                            target_file=target_file,
                                            dependency_type='import',
                                            symbol_name=name,
                                            line_number=line_num,
                                            weight=0.8
                                        ))
                    else:
                        # For other languages, extract the imported path
                        imported_path = match.group(1)
                        if imported_path:
                            # Try to resolve to actual file
                            target_file = self._resolve_import_path(file_path, imported_path)
                            if target_file:
                                dependencies.append(DependencyEdge(
                                    source_file=file_path,
                                    target_file=target_file,
                                    dependency_type='import',
                                    symbol_name=imported_path,
                                    line_number=line_num,
                                    weight=0.8
                                ))

        return dependencies

    def _extract_config_dependencies(self, file_path: Path) -> List[DependencyEdge]:
        """Extract dependencies from configuration files."""
        dependencies = []

        parser = self.config_parsers.get(file_path.name)
        if not parser:
            return dependencies

        try:
            config_deps = parser(file_path)
            for dep in config_deps:
                dependencies.append(DependencyEdge(
                    source_file=file_path,
                    target_file=Path(dep['name']),  # Simplified - in reality would resolve to actual files
                    dependency_type='configuration',
                    dependency_spec=dep.get('version'),
                    line_number=dep.get('line_number', 0),
                    weight=0.6,  # Configuration dependencies are typically weaker than direct imports
                    is_resolved=False  # Configuration dependencies need resolution
                ))
        except (OSError, IOError, json.JSONDecodeError, toml.TomlDecodeError):
            # If we can't parse the config file, skip it
            pass

        return dependencies

    def _resolve_import_path(self, file_path: Path, import_name: str) -> Optional[Path]:
        """
        Resolve an import name to an actual file path.

        Args:
            file_path: Path to the file containing the import
            import_name: The imported module/name

        Returns:
            Resolved file path if found, None otherwise
        """
        if not import_name:
            return None

        # Handle relative imports
        if import_name.startswith('.'):
            # Relative import - resolve relative to file's directory
            base_dir = file_path.parent
            # Count leading dots to determine how many levels to go up
            levels_up = 0
            for char in import_name:
                if char == '.':
                    levels_up += 1
                else:
                    break
            # Go up the specified number of levels (levels_up - 1 for Python relative imports)
            resolved_dir = base_dir
            for _ in range(max(0, levels_up - 1)):
                resolved_dir = resolved_dir.parent
                if not resolved_dir.exists() or not resolved_dir.is_dir():
                    return None

            # Remove the dots from import_name
            relative_part = import_name[levels_up:]
            if relative_part.startswith('/') or relative_part.startswith('\\'):
                relative_part = relative_part[1:]

            # Construct potential file paths
            potential_paths = [
                resolved_dir / (relative_part.replace('.', '/') + '.py'),
                resolved_dir / relative_part.replace('.', '/') / '__init__.py',
                resolved_dir / (relative_part + '.py'),
            ]

            for path in potential_paths:
                if path.exists() and path.is_file():
                    return path

            return None
        else:
            # Absolute import or module name
            # Try to find the file in common locations
            base_dir = Path(self.workspace.workspace_root)

            # Convert module notation to path notation
            module_path = import_name.replace('.', '/')

            # Try common file extensions and locations
            potential_paths = [
                base_dir / (module_path + '.py'),
                base_dir / module_path / '__init__.py',
                base_dir / (module_path + '.js'),
                base_dir / module_path / 'index.js',
                base_dir / (module_path + '.ts'),
                base_dir / module_path / 'index.ts',
                base_dir / (module_path + '.java'),
                base_dir / (module_path.replace('/', '.') + '.java'),  # Java style
            ]

            for path in potential_paths:
                if path.exists() and path.is_file():
                    return path

            return None

    def _is_binary_file(self, file_path: Path) -> bool:
        """Check if a file is binary."""
        try:
            with open(file_path, 'rb') as f:
                chunk = f.read(1024)
                # Check for null bytes or high percentage of non-printable characters
                if b'\x00' in chunk:
                    return True

                # Count printable ASCII characters
                printable = sum(1 for byte in chunk if 32 <= byte <= 126 or byte in (9, 10, 13))  # tab, newline, carriage return
                if len(chunk) > 0 and (printable / len(chunk)) < 0.3:  # Less than 30% printable
                    return True

                return False
        except (OSError, IOError):
            return False

    def _is_large_file(self, file_path: Path, size_lines: int, size_bytes: int) -> bool:
        """Check if a file is large."""
        # Consider files larger than 1000 lines or 100KB as large
        return size_lines > 1000 or size_bytes > 100 * 1024

    def _is_generated_file(self, file_path: Path) -> Dict[str, Any]:
        """
        Check if a file is generated.

        Returns:
            Dictionary with 'is_generated' boolean, 'confidence' float, and 'reasons' list
        """
        result = {
            'is_generated': False,
            'confidence': 0.0,
            'reasons': []
        }

        try:
            # Check file name patterns
            file_name = file_path.name.lower()
            for pattern in self.generated_patterns:
                if re.search(pattern, file_name):
                    result['is_generated'] = True
                    result['confidence'] = max(result['confidence'], 0.9)
                    result['reasons'].append(f"Matches generated pattern: {pattern}")
                    break

            # Check directory path
            path_parts = file_path.parts
            for part in path_parts:
                if part.lower() in self.generated_dirs:
                    result['is_generated'] = True
                    result['confidence'] = max(result['confidence'], 0.8)
                    result['reasons'].append(f"Located in generated directory: {part}")
                    break

            # Check file headers
            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    first_lines = [f.readline().rstrip('\\n\\r') for _ in range(min(10, sum(1 for _ in f)))]
                    f.seek(0)
                    first_lines = [f.readline().rstrip('\\n\\r') for _ in range(10)]

                for line in first_lines:
                    for header_pattern in self.generated_file_headers:
                        if re.search(header_pattern, line, re.IGNORECASE):
                            result['is_generated'] = True
                            result['confidence'] = max(result['confidence'], 0.95)
                            result['reasons'].append(f"Contains generated file header: {header_pattern}")
                            break
                    if result['is_generated']:
                        break
            except (OSError, IOError):
                pass

        except (OSError, IOError):
            pass

        return result

    def _analyze_file_dependencies_cached(self, file_path: Path) -> List[DependencyEdge]:
        """Get dependencies for a file, using cache."""
        if file_path in self._dependency_cache:
            return self._dependency_cache[file_path]

        return self.analyze_file_dependencies(file_path)

    def _parse_package_json(self, file_path: Path) -> List[Dict[str, Any]]:
        """Parse package.json for dependencies."""
        dependencies = []

        try:
            with open(file_path, 'r') as f:
                data = json.load(f)

            # Check both dependencies and devDependencies
            for dep_type in ['dependencies', 'devDependencies', 'peerDependencies']:
                if dep_type in data:
                    for name, version in data[dep_type].items():
                        dependencies.append({
                            'name': name,
                            'version': version,
                            'type': dep_type,
                            'line_number': 0  # Simplified - would need more complex parsing to get line numbers
                        })
        except (OSError, IOError, json.JSONDecodeError):
            pass

        return dependencies

    def _parse_cargo_toml(self, file_path: Path) -> List[Dict[str, Any]]:
        """Parse Cargo.toml for dependencies."""
        dependencies = []

        try:
            with open(file_path, 'r') as f:
                data = toml.load(f)

            # Check various dependency sections
            for section in ['dependencies', 'dev-dependencies', 'build-dependencies']:
                if section in data:
                    for name, dep_info in data[section].items():
                        version = dep_info if isinstance(dep_info, str) else dep_info.get('version', '')
                        dependencies.append({
                            'name': name,
                            'version': version,
                            'type': section,
                            'line_number': 0  # Simplified
                        })
        except (OSError, IOError, toml.TomlDecodeError):
            pass

        return dependencies

    def _parse_pom_xml(self, file_path: Path) -> List[Dict[str, Any]]:
        """Parse pom.xml for dependencies (simplified)."""
        # For simplicity, we'll just return an empty list
        # A full implementation would parse XML
        return []

    def _parse_requirements_txt(self, file_path: Path) -> List[Dict[str, Any]]:
        """Parse requirements.txt for dependencies."""
        dependencies = []

        try:
            with open(file_path, 'r') as f:
                lines = f.readlines()

            for line_num, line in enumerate(lines, 1):
                line = line.strip()
                if line and not line.startswith('#'):
                    # Parse requirement line (simplified)
                    # Handle formats like: package==1.0.0, package>=1.0, package, etc.
                    parts = re.split(r'[<>=!~]', line, 1)
                    name = parts[0].strip()
                    if name:
                        version = line[len(name):].strip() if len(line) > len(name) else ''
                        dependencies.append({
                            'name': name,
                            'version': version,
                            'type': 'requirement',
                            'line_number': line_num
                        })
        except (OSError, IOError):
            pass

        return dependencies

    def _parse_setup_py(self, file_path: Path) -> List[Dict[str, Any]]:
        """Parse setup.py for dependencies (simplified)."""
        # For simplicity, we'll just return an empty list
        # A full implementation would parse Python code or use ast
        return []

    def _parse_poetry_lock(self, file_path: Path) -> List[Dict[str, Any]]:
        """Parse poetry.lock for dependencies (simplified)."""
        # For simplicity, we'll just return an empty list
        # A full implementation would parse TOML
        return []

    def get_all_symbols(self, file_paths: List[Path]) -> Dict[Path, List[Symbol]]:
        """Get all symbols for the given files."""
        symbols = {}
        for file_path in file_paths:
            if self._is_within_workspace(file_path):
                symbols[file_path] = self.analyze_file_symbols(file_path)
        return symbols

    def get_all_dependencies(self, file_paths: List[Path]) -> Dict[Path, List[DependencyEdge]]:
        """Get all dependencies for the given files."""
        dependencies = {}
        for file_path in file_paths:
            if self._is_within_workspace(file_path):
                dependencies[file_path] = self.analyze_file_dependencies(file_path)
        return dependencies

    def clear_cache(self):
        """Clear all caches."""
        self._symbol_cache.clear()
        self._dependency_cache.clear()
        self._special_file_cache.clear()


# Convenience function for easy instantiation
def create_symbol_dependency_analyzer(workspace) -> SymbolDependencyAnalyzer:
    """
    Create a symbol and dependency analyzer.

    Args:
        workspace: Workspace object providing boundary information

    Returns:
        Configured SymbolDependencyAnalyzer instance
    """
    return SymbolDependencyAnalyzer(workspace)


# Export main classes
__all__ = [
    "Symbol",
    "DependencyEdge",
    "SpecialFileClassification",
    "SymbolDependencyAnalyzer",
    "create_symbol_dependency_analyzer"
]